### PR TITLE
home data on frontend

### PR DESCRIPTION
**Pull request by Edgoze**
So right now the data makes it to frontend, I haven't done the randomization of which movies and books get into the carousel, and I still have to put them in the same list (right now all I'm doing is querying for them and doing useState() to save them).
Weird thing: the queries are running twice each... not sure why. Can look more into it later but just wanted to put the progress so far out here.
Also, found a typo in one of the queries: it should be "genres" not "genre"

### CODE REVIEW

**Comment by Edgoze** [comment]
Oh actually it looks like I pushed most of the home stuff to master already, all I did here was changing the port to 8080 and correcting the typo in server.js

**Review by jxiao — COMMENTED** [review]
Regarding why it's running `useEffect` twice, my best guess is that React.StrictMode is turned on somehow.

This isn't an issue -- StrictMode is a dev tool that doesn't affect production code. It's a tool to detect unsafe lifecycles and other dev issues.  In our case, it's fine if we're making a request twice -- we only care about one of them.

**Comment by jxiao** [comment]
Pushed some updates -- The queries take a long time so it looks very plain at first.  After a while, the page will load with details.

**Review by jxiao — APPROVED** [review]
the frontend is mostly there so I think this is good to merge -- we'll do optimizations in another PR

**Pull request merged**
